import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { Body, Button, Card, ComingSoon, Header, Navbar } from "@components";
import {} from "@components/uliran/UliranB";
import { SponsorContactPerson } from "@components/sponsor/SponsorContactPerson";
import { SponsorSponsorship } from "@components/sponsor/SponsorSponsorship";
import { SponsorMediaPartner } from "@components/sponsor/SponsorMediaPartner";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sponsorship</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-powder-light justify-center items-center pt-24 pb-20">
        <div className="flex flex-col gap-8">
          <Header
            preset="h3"
            className="text-center font-black tablet:text-[38px] desktop:text-[48px] pt-4 pb-2"
          >
            Depok Kita Partnership
          </Header>

          <SponsorSponsorship />
          <SponsorMediaPartner />
          <div className="pt-4">
            <SponsorContactPerson />
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
