import type { NextPage } from "next";
import Head from "next/head";
import { ComingSoon, Button, Toast } from "@components";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Toast preset="error" active="on">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </Toast>
      <Toast preset="warning" active="off">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </Toast>
      <Toast preset="success" active="on">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </Toast>
      <Toast preset="info" active="off">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </Toast>

      <ComingSoon />
    </div>
  );
};

export default Home;
