import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "@chakra-ui/react";
import { Toast } from "../components/toast/Toast";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-9xl text-powder">Depok Kita</div>
      <Button colorScheme={"mustard"}>TESSSSS</Button>
      <Toast preset="error">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </Toast>
      <br />
      <br />
      <Toast preset="warning">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </Toast>
      <br />
      <br />
      <Toast preset="success">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </Toast>
      <br />
      <br />
      <Toast preset="info">
        Lorem ipsum dolor sit amet, consectetur adipiscing elit.
      </Toast>

      <svg
        width="30"
        height="27"
        viewBox="0 0 30 27"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
      >
        <path
          d="M15.0759 6.13231L25.2307 23.6774H4.92104L15.0759 6.13231ZM15.0759 0.751465L0.241455 26.3745H29.9103L15.0759 0.751465ZM16.4244 19.6316H13.7273V22.3288H16.4244V19.6316ZM16.4244 11.5401H13.7273V16.9345H16.4244V11.5401Z"
          fill="#DB4333"
        />
      </svg>
    </div>
  );
};

export default Home;
