import type { NextPage } from "next";
import Head from "next/head";
import { ComingSoon, Navbar, Button } from "@components";
import axios from "axios";
const Home: NextPage = () => {
  const handle = () => {
    axios
      .post("/api/grand-launching", {
        data: { name: "marcellinus" },
      })
      .then((response) => {
        console.log(response);
      });
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ComingSoon />
      <Button preset="primaryDark" onClick={handle}>
        haha
      </Button>
    </div>
  );
};

export default Home;
